### ISSUE TITLE
Inexplicable error response creating a thread comment.

### ISSUE THREAD

**Issue by ralphbecket** [koglerjs/threaditjs#7]
Hi, I'm testing a new ThreadIt client I've written.  When I send a request to http://api.threadit.com/comments/create (method: POST, payload: {"text":"asdasdfa", "parent":"RaxJjo"}) I get an error response with the following message:

> TypeError: Cannot call method &#39;replace&#39; of undefined<br>Please report this to https://github.com/chjj/marked.<br> &nbsp; &nbsp;at Lexer.lex (/home/ec2-user/threaditjs/node_modules/marked/lib/marked.js:138:6)<br> &nbsp; &nbsp;at Function.Lexer.lex (/home/ec2-user/threaditjs/node_modules/marked/lib/marked.js:129:16)<br> &nbsp; &nbsp;at marked (/home/ec2-user/threaditjs/node_modules/marked/lib/marked.js:1218:31)<br> &nbsp; &nbsp;at Object.module.exports.newComment (/home/ec2-user/threaditjs/lib/threads.js:142:10)<br> &nbsp; &nbsp;at module.exports (/home/ec2-user/threaditjs/lib/api.js:110:24)<br> &nbsp; &nbsp;at Layer.handle [as handle_request](/home/ec2-user/threaditjs/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/home/ec2-user/threaditjs/node_modules/express/lib/router/route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (/home/ec2-user/threaditjs/node_modules/express/lib/router/route.js:112:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request](/home/ec2-user/threaditjs/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at /home/ec2-user/threaditjs/node_modules/express/lib/router/index.js:277:22

Any advice?

**Comment by koglerjs** [comment]
If you're sending it to threadit.com as in the link you provided, you're
hitting some other site.  The error log looks like it belongs to
threaditjs.com though.  I'll take a look.  That payload format looks
correct, though I don't know what library you're using for the ajax.  It
certainly looks like the api's trying to operate on empty text.

**Comment by ralphbecket** [comment]
I'm just using plain old XMLHTTPRequest with `xhr.send(JSON.stringify({text: ..., parent: ...})`.

**Comment by koglerjs** [comment]
I know that the Azalea implementation does it the same way, perhaps you can
check it out and see what it's doing differently.

https://github.com/koglerjs/threaditjs/blob/master/examples/azalea/app.js

The api should probably throw a better error if there is empty text.

**Comment by ralphbecket** [comment]
Ah, the Azalea code is using "form encoding" ('text=...&parent=...') rather than posting a plain JSON object ('{"text":"...", "parent":"..."}') as the request body.

**Comment by koglerjs** [comment]
I've made a note to add better validation/error communication to parts of
the API like this.

**Comment by ralphbecket** [comment]
Right, success: if I use the POST method, I have to
* use `text=...&parent=...` as the message body **and**
* specify `Content-type: application/x-www-form-urlencoded` in the request header.
otherwise you get the mysterious error report I posted above.
